[
  # from test/support/router.ex
  {"deps/phoenix/lib/phoenix/router.ex", "Function Phoenix.Router.__call__/5 does not exist."},
  {"deps/phoenix/lib/phoenix/router.ex", "Function Phoenix.Router.MalformedURIError.exception/1 does not exist."},
  {"deps/phoenix/lib/phoenix/router.ex", "Function Phoenix.Router.NoRouteError.exception/1 does not exist."},
  {"test/support/router.ex", "Function Phoenix.Router.Helpers.encode_param/1 does not exist."},
  {"test/support/router.ex", "Function Phoenix.Router.Helpers.raise_route_error/6 does not exist."},
  {"test/support/router.ex", "Function Phoenix.Controller.put_new_layout/2 does not exist."},
  {"test/support/router.ex", "Function Phoenix.Controller.put_new_view/2 does not exist."},
  {"test/support/router.ex", "Function Phoenix.Controller.Pipeline.__catch__/5 does not exist."},
  {"test/support/router.ex", "Function Phoenix.Param.to_param/1 does not exist."},
  {"test/support/router.ex", "Function Phoenix.Router.Route.merge_params/2 does not exist."},
  {"test/support/router.ex", "Function Phoenix.VerifiedRoutes.static_integrity/2 does not exist."},
  {"test/support/router.ex", "Function Phoenix.VerifiedRoutes.static_path/2 does not exist."},
  {"test/support/router.ex", "Function Phoenix.VerifiedRoutes.static_url/2 does not exist."},
  {"test/support/router.ex", "Function Phoenix.VerifiedRoutes.unverified_path/3 does not exist."},
  {"test/support/router.ex", "Function Phoenix.VerifiedRoutes.unverified_url/2 does not exist."}
]
